version: '3.8'

services:
  backend:
    build: ./pl-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      NODE_ENV: production
      MONGO_DB_URI: mongodb://mongodb:${MONGO_PORT}/pl
    depends_on:
      - mongodb

  frontend:
    build: ./pl-frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend

  mongodb:
    image: mongo
    restart: always
    expose:
      - "${MONGO_PORT}"
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
    driver: local