version: '3.8'

services:
  pl-backend:
    build: ./pl-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - mongodb

  pl-frontend:
    build: ./pl-frontend
    ports:
      - "8080:8080"
    depends_on:
      - pl-backend

  mongodb:
    image: mongo
    restart: always
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db



volumes:
  mongodb-data:
    driver: local
